export const E2E = {
  panelToggle: "panel-toggle",
  panelContainer: "panel-container",
  panelSheetHandle: "panel-sheet-handle",
  panelTablist: "panel-tablist",
  panelLegend: "panel-legend",
  desktopLegend: "desktop-legend",
  mobileLegendTrigger: "mobile-legend-trigger",
  mobileLegendContent: "mobile-legend-content",
  panelTab: {
    layers: "panel-tab-layers",
    ask: "panel-tab-ask",
  },
  dataLoadError: "data-load-error",
  retryDataLoad: "retry-data-load",
  settingsMenuTrigger: "settings-menu-trigger",
  settingsMenuContent: "settings-menu-content",
  mapView: "map-view",
  locationSearchInput: "location-search-input",
  basemapOption: {
    street: "basemap-option-street",
    satellite: "basemap-option-satellite",
    topo: "basemap-option-topo",
  },
  themeOption: {
    system: "theme-option-system",
    light: "theme-option-light",
    dark: "theme-option-dark",
  },
  layerToggle: {
    townships: "layer-toggle-townships",
    nearestTransit: "layer-toggle-nearest-transit",
    rapidRail: "layer-toggle-rapid-rail",
  },
  townshipPopup: "township-popup",
} as const;
